/**
 * Workflow API for Cloud Foundry
 * This API uses the SAP Cloud Platform Workflow service. With the API, you can, for example, start new workflow instances and work with tasks.  Note (relevant only for SAP API Business Hub): For authentication purposes, the API uses OAuth 2.0 security (with JSON Web Token, JWT). Thus, \"Try Out\" only works with an explicitly configured environment. For more information on how to obtain the necessary parameters, please see [Determine Service Configuration Parameters](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/abb1f66b2c3b4983b6b656654cfc3d2b.html) in the documentation. The OAuth client you use must have [extended scopes](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/baf2847f6d1c401a83ca3a1427b8ff84.html).  Note: These APIs are designed for loosely coupled clients. This means:  - If workflow service adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { ConsumingWorkflowInstance } from '../model';
import { SendMessagePayload } from '../model';
/**
 * MessagesApi - axios parameter creator
 * @export
 */
export declare const MessagesApiAxiosParamCreator: (configuration?: Configuration | undefined) => {
    /**
     * Sends a message to a set of workflow instances for consumption in intermediate message events. The message is identified by the name specified in the workflow model (request body parameter \'definitionId\')  and parameters identifying the workflow instances that should consume the message.   The message is consumed by the workflow instances that match the following criteria:  * The instance can be a specific match when using its workflow instance ID (request body parameter \'workflowInstanceId\').  Or the instance is a generic match when using the ID of the workflow model together with the business key (request body parameters \'workflowDefinitionId\' respectively \'businessKey\'). You can either use the specific or generic match but not both in the same call.  * The workflow instance is not in the SUSPENDED state.  * The workflow instance currently waits at the intermediate message event referring to the specified message.  The business key of a workflow instance matches if the business key specified in the request body is the same.    Roles permitted to execute this operation:  - Global roles:  WorkflowMessageSender  - Scope: MESSAGE_SEND
     * @summary Send message
     * @param {SendMessagePayload} sendMessagePayload Specify the request body according to the given schema. The length of the request body is limited to ensure optimal operation of the service.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createV1Messages: (sendMessagePayload: SendMessagePayload, options?: any) => Promise<RequestArgs>;
};
/**
 * MessagesApi - functional programming interface
 * @export
 */
export declare const MessagesApiFp: (configuration?: Configuration | undefined) => {
    /**
     * Sends a message to a set of workflow instances for consumption in intermediate message events. The message is identified by the name specified in the workflow model (request body parameter \'definitionId\')  and parameters identifying the workflow instances that should consume the message.   The message is consumed by the workflow instances that match the following criteria:  * The instance can be a specific match when using its workflow instance ID (request body parameter \'workflowInstanceId\').  Or the instance is a generic match when using the ID of the workflow model together with the business key (request body parameters \'workflowDefinitionId\' respectively \'businessKey\'). You can either use the specific or generic match but not both in the same call.  * The workflow instance is not in the SUSPENDED state.  * The workflow instance currently waits at the intermediate message event referring to the specified message.  The business key of a workflow instance matches if the business key specified in the request body is the same.    Roles permitted to execute this operation:  - Global roles:  WorkflowMessageSender  - Scope: MESSAGE_SEND
     * @summary Send message
     * @param {SendMessagePayload} sendMessagePayload Specify the request body according to the given schema. The length of the request body is limited to ensure optimal operation of the service.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createV1Messages(sendMessagePayload: SendMessagePayload, options?: any): Promise<(axios?: AxiosInstance | undefined, basePath?: string | undefined) => AxiosPromise<Array<ConsumingWorkflowInstance>>>;
};
/**
 * MessagesApi - factory interface
 * @export
 */
export declare const MessagesApiFactory: (configuration?: Configuration | undefined, basePath?: string | undefined, axios?: AxiosInstance | undefined) => {
    /**
     * Sends a message to a set of workflow instances for consumption in intermediate message events. The message is identified by the name specified in the workflow model (request body parameter \'definitionId\')  and parameters identifying the workflow instances that should consume the message.   The message is consumed by the workflow instances that match the following criteria:  * The instance can be a specific match when using its workflow instance ID (request body parameter \'workflowInstanceId\').  Or the instance is a generic match when using the ID of the workflow model together with the business key (request body parameters \'workflowDefinitionId\' respectively \'businessKey\'). You can either use the specific or generic match but not both in the same call.  * The workflow instance is not in the SUSPENDED state.  * The workflow instance currently waits at the intermediate message event referring to the specified message.  The business key of a workflow instance matches if the business key specified in the request body is the same.    Roles permitted to execute this operation:  - Global roles:  WorkflowMessageSender  - Scope: MESSAGE_SEND
     * @summary Send message
     * @param {SendMessagePayload} sendMessagePayload Specify the request body according to the given schema. The length of the request body is limited to ensure optimal operation of the service.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createV1Messages(sendMessagePayload: SendMessagePayload, options?: any): AxiosPromise<Array<ConsumingWorkflowInstance>>;
};
/**
 * MessagesApi - object-oriented interface
 * @export
 * @class MessagesApi
 * @extends {BaseAPI}
 */
export declare class MessagesApi extends BaseAPI {
    /**
     * Sends a message to a set of workflow instances for consumption in intermediate message events. The message is identified by the name specified in the workflow model (request body parameter \'definitionId\')  and parameters identifying the workflow instances that should consume the message.   The message is consumed by the workflow instances that match the following criteria:  * The instance can be a specific match when using its workflow instance ID (request body parameter \'workflowInstanceId\').  Or the instance is a generic match when using the ID of the workflow model together with the business key (request body parameters \'workflowDefinitionId\' respectively \'businessKey\'). You can either use the specific or generic match but not both in the same call.  * The workflow instance is not in the SUSPENDED state.  * The workflow instance currently waits at the intermediate message event referring to the specified message.  The business key of a workflow instance matches if the business key specified in the request body is the same.    Roles permitted to execute this operation:  - Global roles:  WorkflowMessageSender  - Scope: MESSAGE_SEND
     * @summary Send message
     * @param {SendMessagePayload} sendMessagePayload Specify the request body according to the given schema. The length of the request body is limited to ensure optimal operation of the service.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    createV1Messages(sendMessagePayload: SendMessagePayload, options?: any): Promise<import("axios").AxiosResponse<ConsumingWorkflowInstance[]>>;
}
//# sourceMappingURL=messages-api.d.ts.map