/* tslint:disable */
/* eslint-disable */
/**
 * Workflow API for Cloud Foundry
 * This API uses the SAP Cloud Platform Workflow service. With the API, you can, for example, start new workflow instances and work with tasks.  Note (relevant only for SAP API Business Hub): For authentication purposes, the API uses OAuth 2.0 security (with JSON Web Token, JWT). Thus, \"Try Out\" only works with an explicitly configured environment. For more information on how to obtain the necessary parameters, please see [Determine Service Configuration Parameters](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/abb1f66b2c3b4983b6b656654cfc3d2b.html) in the documentation. The OAuth client you use must have [extended scopes](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/baf2847f6d1c401a83ca3a1427b8ff84.html).  Note: These APIs are designed for loosely coupled clients. This means:  - If workflow service adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { SampleContext } from '../model';
// @ts-ignore
import { TechnicalError } from '../model';
// @ts-ignore
import { UnauthorizedError } from '../model';
// @ts-ignore
import { WorkflowDefinition } from '../model';
// @ts-ignore
import { WorkflowDefinitionVersion } from '../model';
// @ts-ignore
import { WorkflowModel } from '../model';
/**
 * WorkflowDefinitionsApi - axios parameter creator
 * @export
 */
export const WorkflowDefinitionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Undeploys all versions of an existing workflow definition and deletes the corresponding workflow instances. Once the undeployment has started, you can no longer start a new workflow instance based on this workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowTenantOperator  - Scope: WORKFLOW_DEFINITION_UNDEPLOY 
         * @summary Delete workflow definition
         * @param {string} definitionId The ID of the workflow definition to be undeployed. The ID is at most 64 characters long.
         * @param {boolean} [cascade] Whether the undeployment of the workflow definition deletes active workflow instances. If the parameter is false or not specified and there are active workflow instances for the specified workflow definition,  the undeployment is rejected. An instance is considered active if it is in status RUNNING, ERRONEOUS, or SUSPENDED. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteV1WorkflowDefinitionsByDefinitionId: async (definitionId: string, cascade?: boolean, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'definitionId' is not null or undefined
            if (definitionId === null || definitionId === undefined) {
                throw new RequiredError('definitionId','Required parameter definitionId was null or undefined when calling deleteV1WorkflowDefinitionsByDefinitionId.');
            }
            const localVarPath = `/v1/workflow-definitions/{definitionId}`
                .replace(`{${"definitionId"}}`, encodeURIComponent(String(definitionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Oauth2_AuthorizationCode required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_AuthorizationCode", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication Oauth2_ClientCredentials required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_ClientCredentials", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if (cascade !== undefined) {
                localVarQueryParameter['cascade'] = cascade;
            }


    
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a list of the latest version of each deployed workflow definition. The request can be parameterized.  Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve all workflow definitions
         * @param {'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc'} [$orderby] Specify the attribute you want to sort by and the order separated by a space. If the order is omitted it is ascending by default. If not specified, the results are sorted by the \&#39;createdAt\&#39; attribute in descending order.
         * @param {number} [$skip] Specify the number of records you want to skip from the beginning. You can skip at most 4000 records. To indicate a result range that starts, for example, at 1001, combine the $skip with the $top parameter. If not specified, no records are skipped. Refer also to the $top parameter.
         * @param {number} [$top] Specify the number of records you want to show. You can get at most 1000 records per API call. To indicate a result range that starts, for example, at 1001, combine the $top with the $skip parameter. If not specified, 100 records are returned. Refer also to the $skip parameter.
         * @param {'allpages' | 'none'} [$inlinecount] Specify whether the total count of the workflow definitions should be returned as the value of the X-Total-Count response header. To enable the header, use the \&#39;allpages\&#39; setting. To disable the header, use the \&#39;none\&#39; setting. The values are case-sensitive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitions: async ($orderby?: 'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc', $skip?: number, $top?: number, $inlinecount?: 'allpages' | 'none', options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/workflow-definitions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Oauth2_AuthorizationCode required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_AuthorizationCode", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication Oauth2_ClientCredentials required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_ClientCredentials", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if ($orderby !== undefined) {
                localVarQueryParameter['$orderby'] = $orderby;
            }

            if ($skip !== undefined) {
                localVarQueryParameter['$skip'] = $skip;
            }

            if ($top !== undefined) {
                localVarQueryParameter['$top'] = $top;
            }

            if ($inlinecount !== undefined) {
                localVarQueryParameter['$inlinecount'] = $inlinecount;
            }


    
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the latest version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:   WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve workflow definition by ID
         * @param {string} definitionId The ID of the workflow definition for which the latest version should be retrieved. The ID is at most 64 characters long.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsByDefinitionId: async (definitionId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'definitionId' is not null or undefined
            if (definitionId === null || definitionId === undefined) {
                throw new RequiredError('definitionId','Required parameter definitionId was null or undefined when calling getV1WorkflowDefinitionsByDefinitionId.');
            }
            const localVarPath = `/v1/workflow-definitions/{definitionId}`
                .replace(`{${"definitionId"}}`, encodeURIComponent(String(definitionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Oauth2_AuthorizationCode required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_AuthorizationCode", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication Oauth2_ClientCredentials required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_ClientCredentials", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the model of the latest version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET_MODEL 
         * @summary Retrieve workflow definition model by ID
         * @param {string} definitionId The workflow definition ID for which the latest model should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsModelByDefinitionId: async (definitionId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'definitionId' is not null or undefined
            if (definitionId === null || definitionId === undefined) {
                throw new RequiredError('definitionId','Required parameter definitionId was null or undefined when calling getV1WorkflowDefinitionsModelByDefinitionId.');
            }
            const localVarPath = `/v1/workflow-definitions/{definitionId}/model`
                .replace(`{${"definitionId"}}`, encodeURIComponent(String(definitionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Oauth2_AuthorizationCode required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_AuthorizationCode", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication Oauth2_ClientCredentials required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_ClientCredentials", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the default start context of the latest version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowInitiator  - Scope: WORKFLOW_DEFINITION_GET_SAMPLE_CONTEXT 
         * @summary Retrieve sample start context of workflow definition by ID
         * @param {string} definitionId The workflow definition ID for which the default start context should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId: async (definitionId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'definitionId' is not null or undefined
            if (definitionId === null || definitionId === undefined) {
                throw new RequiredError('definitionId','Required parameter definitionId was null or undefined when calling getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId.');
            }
            const localVarPath = `/v1/workflow-definitions/{definitionId}/sample-contexts/default-start-context`
                .replace(`{${"definitionId"}}`, encodeURIComponent(String(definitionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Oauth2_AuthorizationCode required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_AuthorizationCode", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication Oauth2_ClientCredentials required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_ClientCredentials", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a list of all deployed versions of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve all versions of workflow definition by ID
         * @param {string} definitionId The ID of the workflow definition for which all versions should be retrieved. The ID is at most 64 characters long.
         * @param {'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc'} [$orderby] Specify the attribute you want to sort by and the order separated by a space. If the order is omitted it is ascending by default. If not specified, the results are sorted by the \&#39;createdAt\&#39; attribute in descending order.
         * @param {number} [$skip] Specify the number of records you want to skip from the beginning. You can skip at most 4000 records. To indicate a result range that starts, for example, at 1001, combine the $skip with the $top parameter. If not specified, no records are skipped. Refer also to the $top parameter.
         * @param {number} [$top] Specify the number of records you want to show. You can get at most 1000 records per API call. To indicate a result range that starts, for example, at 1001, combine the $top with the $skip parameter. If not specified, 100 records are returned. Refer also to the $skip parameter.
         * @param {'allpages' | 'none'} [$inlinecount] Specify whether the total count of the workflow definition versions should be returned as the value of the X-Total-Count response header. To enable the header, use the \&#39;allpages\&#39; setting. To disable the header, use the \&#39;none\&#39; setting. The values are case-sensitive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsVersionsByDefinitionId: async (definitionId: string, $orderby?: 'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc', $skip?: number, $top?: number, $inlinecount?: 'allpages' | 'none', options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'definitionId' is not null or undefined
            if (definitionId === null || definitionId === undefined) {
                throw new RequiredError('definitionId','Required parameter definitionId was null or undefined when calling getV1WorkflowDefinitionsVersionsByDefinitionId.');
            }
            const localVarPath = `/v1/workflow-definitions/{definitionId}/versions`
                .replace(`{${"definitionId"}}`, encodeURIComponent(String(definitionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Oauth2_AuthorizationCode required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_AuthorizationCode", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication Oauth2_ClientCredentials required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_ClientCredentials", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            if ($orderby !== undefined) {
                localVarQueryParameter['$orderby'] = $orderby;
            }

            if ($skip !== undefined) {
                localVarQueryParameter['$skip'] = $skip;
            }

            if ($top !== undefined) {
                localVarQueryParameter['$top'] = $top;
            }

            if ($inlinecount !== undefined) {
                localVarQueryParameter['$inlinecount'] = $inlinecount;
            }


    
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the specified version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve workflow definition by ID and version number
         * @param {string} definitionId The ID of the workflow definition which should be retrieved. The ID is at most 64 characters long.
         * @param {string} versionNumber The version number of the workflow definition that should be retrieved. The version number consists of 1 - 10 digits.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber: async (definitionId: string, versionNumber: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'definitionId' is not null or undefined
            if (definitionId === null || definitionId === undefined) {
                throw new RequiredError('definitionId','Required parameter definitionId was null or undefined when calling getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber.');
            }
            // verify required parameter 'versionNumber' is not null or undefined
            if (versionNumber === null || versionNumber === undefined) {
                throw new RequiredError('versionNumber','Required parameter versionNumber was null or undefined when calling getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber.');
            }
            const localVarPath = `/v1/workflow-definitions/{definitionId}/versions/{versionNumber}`
                .replace(`{${"definitionId"}}`, encodeURIComponent(String(definitionId)))
                .replace(`{${"versionNumber"}}`, encodeURIComponent(String(versionNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Oauth2_AuthorizationCode required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_AuthorizationCode", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication Oauth2_ClientCredentials required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_ClientCredentials", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the model of the specified version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET_MODEL 
         * @summary Retrieve workflow definition model by ID and version number
         * @param {string} definitionId The workflow definition ID for which the model should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {string} versionNumber The version number for which the model should be retrieved. The version number consists of 1 - 10 digits.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber: async (definitionId: string, versionNumber: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'definitionId' is not null or undefined
            if (definitionId === null || definitionId === undefined) {
                throw new RequiredError('definitionId','Required parameter definitionId was null or undefined when calling getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber.');
            }
            // verify required parameter 'versionNumber' is not null or undefined
            if (versionNumber === null || versionNumber === undefined) {
                throw new RequiredError('versionNumber','Required parameter versionNumber was null or undefined when calling getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber.');
            }
            const localVarPath = `/v1/workflow-definitions/{definitionId}/versions/{versionNumber}/model`
                .replace(`{${"definitionId"}}`, encodeURIComponent(String(definitionId)))
                .replace(`{${"versionNumber"}}`, encodeURIComponent(String(versionNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Oauth2_AuthorizationCode required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_AuthorizationCode", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication Oauth2_ClientCredentials required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_ClientCredentials", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the default start context of the specified version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowInitiator  - Scope: WORKFLOW_DEFINITION_GET_SAMPLE_CONTEXT 
         * @summary Retrieve sample start context of workflow definition by ID and version number
         * @param {string} definitionId The workflow definition ID for which the default start context should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {string} versionNumber The version number for which the default start context should be retrieved. The version number consists of 1 - 10 digits.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber: async (definitionId: string, versionNumber: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'definitionId' is not null or undefined
            if (definitionId === null || definitionId === undefined) {
                throw new RequiredError('definitionId','Required parameter definitionId was null or undefined when calling getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber.');
            }
            // verify required parameter 'versionNumber' is not null or undefined
            if (versionNumber === null || versionNumber === undefined) {
                throw new RequiredError('versionNumber','Required parameter versionNumber was null or undefined when calling getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber.');
            }
            const localVarPath = `/v1/workflow-definitions/{definitionId}/versions/{versionNumber}/sample-contexts/default-start-context`
                .replace(`{${"definitionId"}}`, encodeURIComponent(String(definitionId)))
                .replace(`{${"versionNumber"}}`, encodeURIComponent(String(versionNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Oauth2_AuthorizationCode required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_AuthorizationCode", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

            // authentication Oauth2_ClientCredentials required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken("Oauth2_ClientCredentials", [])
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WorkflowDefinitionsApi - functional programming interface
 * @export
 */
export const WorkflowDefinitionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Undeploys all versions of an existing workflow definition and deletes the corresponding workflow instances. Once the undeployment has started, you can no longer start a new workflow instance based on this workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowTenantOperator  - Scope: WORKFLOW_DEFINITION_UNDEPLOY 
         * @summary Delete workflow definition
         * @param {string} definitionId The ID of the workflow definition to be undeployed. The ID is at most 64 characters long.
         * @param {boolean} [cascade] Whether the undeployment of the workflow definition deletes active workflow instances. If the parameter is false or not specified and there are active workflow instances for the specified workflow definition,  the undeployment is rejected. An instance is considered active if it is in status RUNNING, ERRONEOUS, or SUSPENDED. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteV1WorkflowDefinitionsByDefinitionId(definitionId: string, cascade?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await WorkflowDefinitionsApiAxiosParamCreator(configuration).deleteV1WorkflowDefinitionsByDefinitionId(definitionId, cascade, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves a list of the latest version of each deployed workflow definition. The request can be parameterized.  Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve all workflow definitions
         * @param {'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc'} [$orderby] Specify the attribute you want to sort by and the order separated by a space. If the order is omitted it is ascending by default. If not specified, the results are sorted by the \&#39;createdAt\&#39; attribute in descending order.
         * @param {number} [$skip] Specify the number of records you want to skip from the beginning. You can skip at most 4000 records. To indicate a result range that starts, for example, at 1001, combine the $skip with the $top parameter. If not specified, no records are skipped. Refer also to the $top parameter.
         * @param {number} [$top] Specify the number of records you want to show. You can get at most 1000 records per API call. To indicate a result range that starts, for example, at 1001, combine the $top with the $skip parameter. If not specified, 100 records are returned. Refer also to the $skip parameter.
         * @param {'allpages' | 'none'} [$inlinecount] Specify whether the total count of the workflow definitions should be returned as the value of the X-Total-Count response header. To enable the header, use the \&#39;allpages\&#39; setting. To disable the header, use the \&#39;none\&#39; setting. The values are case-sensitive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1WorkflowDefinitions($orderby?: 'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc', $skip?: number, $top?: number, $inlinecount?: 'allpages' | 'none', options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WorkflowDefinition>>> {
            const localVarAxiosArgs = await WorkflowDefinitionsApiAxiosParamCreator(configuration).getV1WorkflowDefinitions($orderby, $skip, $top, $inlinecount, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the latest version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:   WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve workflow definition by ID
         * @param {string} definitionId The ID of the workflow definition for which the latest version should be retrieved. The ID is at most 64 characters long.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1WorkflowDefinitionsByDefinitionId(definitionId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowDefinition>> {
            const localVarAxiosArgs = await WorkflowDefinitionsApiAxiosParamCreator(configuration).getV1WorkflowDefinitionsByDefinitionId(definitionId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the model of the latest version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET_MODEL 
         * @summary Retrieve workflow definition model by ID
         * @param {string} definitionId The workflow definition ID for which the latest model should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1WorkflowDefinitionsModelByDefinitionId(definitionId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowModel>> {
            const localVarAxiosArgs = await WorkflowDefinitionsApiAxiosParamCreator(configuration).getV1WorkflowDefinitionsModelByDefinitionId(definitionId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the default start context of the latest version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowInitiator  - Scope: WORKFLOW_DEFINITION_GET_SAMPLE_CONTEXT 
         * @summary Retrieve sample start context of workflow definition by ID
         * @param {string} definitionId The workflow definition ID for which the default start context should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId(definitionId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SampleContext>> {
            const localVarAxiosArgs = await WorkflowDefinitionsApiAxiosParamCreator(configuration).getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId(definitionId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves a list of all deployed versions of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve all versions of workflow definition by ID
         * @param {string} definitionId The ID of the workflow definition for which all versions should be retrieved. The ID is at most 64 characters long.
         * @param {'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc'} [$orderby] Specify the attribute you want to sort by and the order separated by a space. If the order is omitted it is ascending by default. If not specified, the results are sorted by the \&#39;createdAt\&#39; attribute in descending order.
         * @param {number} [$skip] Specify the number of records you want to skip from the beginning. You can skip at most 4000 records. To indicate a result range that starts, for example, at 1001, combine the $skip with the $top parameter. If not specified, no records are skipped. Refer also to the $top parameter.
         * @param {number} [$top] Specify the number of records you want to show. You can get at most 1000 records per API call. To indicate a result range that starts, for example, at 1001, combine the $top with the $skip parameter. If not specified, 100 records are returned. Refer also to the $skip parameter.
         * @param {'allpages' | 'none'} [$inlinecount] Specify whether the total count of the workflow definition versions should be returned as the value of the X-Total-Count response header. To enable the header, use the \&#39;allpages\&#39; setting. To disable the header, use the \&#39;none\&#39; setting. The values are case-sensitive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1WorkflowDefinitionsVersionsByDefinitionId(definitionId: string, $orderby?: 'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc', $skip?: number, $top?: number, $inlinecount?: 'allpages' | 'none', options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WorkflowDefinitionVersion>>> {
            const localVarAxiosArgs = await WorkflowDefinitionsApiAxiosParamCreator(configuration).getV1WorkflowDefinitionsVersionsByDefinitionId(definitionId, $orderby, $skip, $top, $inlinecount, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the specified version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve workflow definition by ID and version number
         * @param {string} definitionId The ID of the workflow definition which should be retrieved. The ID is at most 64 characters long.
         * @param {string} versionNumber The version number of the workflow definition that should be retrieved. The version number consists of 1 - 10 digits.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber(definitionId: string, versionNumber: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowDefinitionVersion>> {
            const localVarAxiosArgs = await WorkflowDefinitionsApiAxiosParamCreator(configuration).getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber(definitionId, versionNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the model of the specified version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET_MODEL 
         * @summary Retrieve workflow definition model by ID and version number
         * @param {string} definitionId The workflow definition ID for which the model should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {string} versionNumber The version number for which the model should be retrieved. The version number consists of 1 - 10 digits.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber(definitionId: string, versionNumber: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowModel>> {
            const localVarAxiosArgs = await WorkflowDefinitionsApiAxiosParamCreator(configuration).getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber(definitionId, versionNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieves the default start context of the specified version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowInitiator  - Scope: WORKFLOW_DEFINITION_GET_SAMPLE_CONTEXT 
         * @summary Retrieve sample start context of workflow definition by ID and version number
         * @param {string} definitionId The workflow definition ID for which the default start context should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {string} versionNumber The version number for which the default start context should be retrieved. The version number consists of 1 - 10 digits.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber(definitionId: string, versionNumber: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SampleContext>> {
            const localVarAxiosArgs = await WorkflowDefinitionsApiAxiosParamCreator(configuration).getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber(definitionId, versionNumber, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WorkflowDefinitionsApi - factory interface
 * @export
 */
export const WorkflowDefinitionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Undeploys all versions of an existing workflow definition and deletes the corresponding workflow instances. Once the undeployment has started, you can no longer start a new workflow instance based on this workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowTenantOperator  - Scope: WORKFLOW_DEFINITION_UNDEPLOY 
         * @summary Delete workflow definition
         * @param {string} definitionId The ID of the workflow definition to be undeployed. The ID is at most 64 characters long.
         * @param {boolean} [cascade] Whether the undeployment of the workflow definition deletes active workflow instances. If the parameter is false or not specified and there are active workflow instances for the specified workflow definition,  the undeployment is rejected. An instance is considered active if it is in status RUNNING, ERRONEOUS, or SUSPENDED. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteV1WorkflowDefinitionsByDefinitionId(definitionId: string, cascade?: boolean, options?: any): AxiosPromise<void> {
            return WorkflowDefinitionsApiFp(configuration).deleteV1WorkflowDefinitionsByDefinitionId(definitionId, cascade, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a list of the latest version of each deployed workflow definition. The request can be parameterized.  Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve all workflow definitions
         * @param {'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc'} [$orderby] Specify the attribute you want to sort by and the order separated by a space. If the order is omitted it is ascending by default. If not specified, the results are sorted by the \&#39;createdAt\&#39; attribute in descending order.
         * @param {number} [$skip] Specify the number of records you want to skip from the beginning. You can skip at most 4000 records. To indicate a result range that starts, for example, at 1001, combine the $skip with the $top parameter. If not specified, no records are skipped. Refer also to the $top parameter.
         * @param {number} [$top] Specify the number of records you want to show. You can get at most 1000 records per API call. To indicate a result range that starts, for example, at 1001, combine the $top with the $skip parameter. If not specified, 100 records are returned. Refer also to the $skip parameter.
         * @param {'allpages' | 'none'} [$inlinecount] Specify whether the total count of the workflow definitions should be returned as the value of the X-Total-Count response header. To enable the header, use the \&#39;allpages\&#39; setting. To disable the header, use the \&#39;none\&#39; setting. The values are case-sensitive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitions($orderby?: 'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc', $skip?: number, $top?: number, $inlinecount?: 'allpages' | 'none', options?: any): AxiosPromise<Array<WorkflowDefinition>> {
            return WorkflowDefinitionsApiFp(configuration).getV1WorkflowDefinitions($orderby, $skip, $top, $inlinecount, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the latest version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:   WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve workflow definition by ID
         * @param {string} definitionId The ID of the workflow definition for which the latest version should be retrieved. The ID is at most 64 characters long.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsByDefinitionId(definitionId: string, options?: any): AxiosPromise<WorkflowDefinition> {
            return WorkflowDefinitionsApiFp(configuration).getV1WorkflowDefinitionsByDefinitionId(definitionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the model of the latest version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET_MODEL 
         * @summary Retrieve workflow definition model by ID
         * @param {string} definitionId The workflow definition ID for which the latest model should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsModelByDefinitionId(definitionId: string, options?: any): AxiosPromise<WorkflowModel> {
            return WorkflowDefinitionsApiFp(configuration).getV1WorkflowDefinitionsModelByDefinitionId(definitionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the default start context of the latest version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowInitiator  - Scope: WORKFLOW_DEFINITION_GET_SAMPLE_CONTEXT 
         * @summary Retrieve sample start context of workflow definition by ID
         * @param {string} definitionId The workflow definition ID for which the default start context should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId(definitionId: string, options?: any): AxiosPromise<SampleContext> {
            return WorkflowDefinitionsApiFp(configuration).getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId(definitionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a list of all deployed versions of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve all versions of workflow definition by ID
         * @param {string} definitionId The ID of the workflow definition for which all versions should be retrieved. The ID is at most 64 characters long.
         * @param {'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc'} [$orderby] Specify the attribute you want to sort by and the order separated by a space. If the order is omitted it is ascending by default. If not specified, the results are sorted by the \&#39;createdAt\&#39; attribute in descending order.
         * @param {number} [$skip] Specify the number of records you want to skip from the beginning. You can skip at most 4000 records. To indicate a result range that starts, for example, at 1001, combine the $skip with the $top parameter. If not specified, no records are skipped. Refer also to the $top parameter.
         * @param {number} [$top] Specify the number of records you want to show. You can get at most 1000 records per API call. To indicate a result range that starts, for example, at 1001, combine the $top with the $skip parameter. If not specified, 100 records are returned. Refer also to the $skip parameter.
         * @param {'allpages' | 'none'} [$inlinecount] Specify whether the total count of the workflow definition versions should be returned as the value of the X-Total-Count response header. To enable the header, use the \&#39;allpages\&#39; setting. To disable the header, use the \&#39;none\&#39; setting. The values are case-sensitive.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsVersionsByDefinitionId(definitionId: string, $orderby?: 'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc', $skip?: number, $top?: number, $inlinecount?: 'allpages' | 'none', options?: any): AxiosPromise<Array<WorkflowDefinitionVersion>> {
            return WorkflowDefinitionsApiFp(configuration).getV1WorkflowDefinitionsVersionsByDefinitionId(definitionId, $orderby, $skip, $top, $inlinecount, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the specified version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
         * @summary Retrieve workflow definition by ID and version number
         * @param {string} definitionId The ID of the workflow definition which should be retrieved. The ID is at most 64 characters long.
         * @param {string} versionNumber The version number of the workflow definition that should be retrieved. The version number consists of 1 - 10 digits.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber(definitionId: string, versionNumber: string, options?: any): AxiosPromise<WorkflowDefinitionVersion> {
            return WorkflowDefinitionsApiFp(configuration).getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber(definitionId, versionNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the model of the specified version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET_MODEL 
         * @summary Retrieve workflow definition model by ID and version number
         * @param {string} definitionId The workflow definition ID for which the model should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {string} versionNumber The version number for which the model should be retrieved. The version number consists of 1 - 10 digits.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber(definitionId: string, versionNumber: string, options?: any): AxiosPromise<WorkflowModel> {
            return WorkflowDefinitionsApiFp(configuration).getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber(definitionId, versionNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the default start context of the specified version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowInitiator  - Scope: WORKFLOW_DEFINITION_GET_SAMPLE_CONTEXT 
         * @summary Retrieve sample start context of workflow definition by ID and version number
         * @param {string} definitionId The workflow definition ID for which the default start context should be retrieved. The workflow definition ID is at most 64 characters long.
         * @param {string} versionNumber The version number for which the default start context should be retrieved. The version number consists of 1 - 10 digits.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber(definitionId: string, versionNumber: string, options?: any): AxiosPromise<SampleContext> {
            return WorkflowDefinitionsApiFp(configuration).getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber(definitionId, versionNumber, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WorkflowDefinitionsApi - object-oriented interface
 * @export
 * @class WorkflowDefinitionsApi
 * @extends {BaseAPI}
 */
export class WorkflowDefinitionsApi extends BaseAPI {
    /**
     * Undeploys all versions of an existing workflow definition and deletes the corresponding workflow instances. Once the undeployment has started, you can no longer start a new workflow instance based on this workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowTenantOperator  - Scope: WORKFLOW_DEFINITION_UNDEPLOY 
     * @summary Delete workflow definition
     * @param {string} definitionId The ID of the workflow definition to be undeployed. The ID is at most 64 characters long.
     * @param {boolean} [cascade] Whether the undeployment of the workflow definition deletes active workflow instances. If the parameter is false or not specified and there are active workflow instances for the specified workflow definition,  the undeployment is rejected. An instance is considered active if it is in status RUNNING, ERRONEOUS, or SUSPENDED. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowDefinitionsApi
     */
    public deleteV1WorkflowDefinitionsByDefinitionId(definitionId: string, cascade?: boolean, options?: any) {
        return WorkflowDefinitionsApiFp(this.configuration).deleteV1WorkflowDefinitionsByDefinitionId(definitionId, cascade, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a list of the latest version of each deployed workflow definition. The request can be parameterized.  Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
     * @summary Retrieve all workflow definitions
     * @param {'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc'} [$orderby] Specify the attribute you want to sort by and the order separated by a space. If the order is omitted it is ascending by default. If not specified, the results are sorted by the \&#39;createdAt\&#39; attribute in descending order.
     * @param {number} [$skip] Specify the number of records you want to skip from the beginning. You can skip at most 4000 records. To indicate a result range that starts, for example, at 1001, combine the $skip with the $top parameter. If not specified, no records are skipped. Refer also to the $top parameter.
     * @param {number} [$top] Specify the number of records you want to show. You can get at most 1000 records per API call. To indicate a result range that starts, for example, at 1001, combine the $top with the $skip parameter. If not specified, 100 records are returned. Refer also to the $skip parameter.
     * @param {'allpages' | 'none'} [$inlinecount] Specify whether the total count of the workflow definitions should be returned as the value of the X-Total-Count response header. To enable the header, use the \&#39;allpages\&#39; setting. To disable the header, use the \&#39;none\&#39; setting. The values are case-sensitive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowDefinitionsApi
     */
    public getV1WorkflowDefinitions($orderby?: 'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc', $skip?: number, $top?: number, $inlinecount?: 'allpages' | 'none', options?: any) {
        return WorkflowDefinitionsApiFp(this.configuration).getV1WorkflowDefinitions($orderby, $skip, $top, $inlinecount, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the latest version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:   WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
     * @summary Retrieve workflow definition by ID
     * @param {string} definitionId The ID of the workflow definition for which the latest version should be retrieved. The ID is at most 64 characters long.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowDefinitionsApi
     */
    public getV1WorkflowDefinitionsByDefinitionId(definitionId: string, options?: any) {
        return WorkflowDefinitionsApiFp(this.configuration).getV1WorkflowDefinitionsByDefinitionId(definitionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the model of the latest version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET_MODEL 
     * @summary Retrieve workflow definition model by ID
     * @param {string} definitionId The workflow definition ID for which the latest model should be retrieved. The workflow definition ID is at most 64 characters long.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowDefinitionsApi
     */
    public getV1WorkflowDefinitionsModelByDefinitionId(definitionId: string, options?: any) {
        return WorkflowDefinitionsApiFp(this.configuration).getV1WorkflowDefinitionsModelByDefinitionId(definitionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the default start context of the latest version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowInitiator  - Scope: WORKFLOW_DEFINITION_GET_SAMPLE_CONTEXT 
     * @summary Retrieve sample start context of workflow definition by ID
     * @param {string} definitionId The workflow definition ID for which the default start context should be retrieved. The workflow definition ID is at most 64 characters long.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowDefinitionsApi
     */
    public getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId(definitionId: string, options?: any) {
        return WorkflowDefinitionsApiFp(this.configuration).getV1WorkflowDefinitionsSampleContextsDefaultStartContextByDefinitionId(definitionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a list of all deployed versions of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
     * @summary Retrieve all versions of workflow definition by ID
     * @param {string} definitionId The ID of the workflow definition for which all versions should be retrieved. The ID is at most 64 characters long.
     * @param {'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc'} [$orderby] Specify the attribute you want to sort by and the order separated by a space. If the order is omitted it is ascending by default. If not specified, the results are sorted by the \&#39;createdAt\&#39; attribute in descending order.
     * @param {number} [$skip] Specify the number of records you want to skip from the beginning. You can skip at most 4000 records. To indicate a result range that starts, for example, at 1001, combine the $skip with the $top parameter. If not specified, no records are skipped. Refer also to the $top parameter.
     * @param {number} [$top] Specify the number of records you want to show. You can get at most 1000 records per API call. To indicate a result range that starts, for example, at 1001, combine the $top with the $skip parameter. If not specified, 100 records are returned. Refer also to the $skip parameter.
     * @param {'allpages' | 'none'} [$inlinecount] Specify whether the total count of the workflow definition versions should be returned as the value of the X-Total-Count response header. To enable the header, use the \&#39;allpages\&#39; setting. To disable the header, use the \&#39;none\&#39; setting. The values are case-sensitive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowDefinitionsApi
     */
    public getV1WorkflowDefinitionsVersionsByDefinitionId(definitionId: string, $orderby?: 'id' | 'id asc' | 'id desc' | 'version' | 'version asc' | 'version desc' | 'name' | 'name asc' | 'name desc' | 'createdAt' | 'createdAt asc' | 'createdAt desc' | 'createdBy' | 'createdBy asc' | 'createdBy desc', $skip?: number, $top?: number, $inlinecount?: 'allpages' | 'none', options?: any) {
        return WorkflowDefinitionsApiFp(this.configuration).getV1WorkflowDefinitionsVersionsByDefinitionId(definitionId, $orderby, $skip, $top, $inlinecount, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the specified version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET 
     * @summary Retrieve workflow definition by ID and version number
     * @param {string} definitionId The ID of the workflow definition which should be retrieved. The ID is at most 64 characters long.
     * @param {string} versionNumber The version number of the workflow definition that should be retrieved. The version number consists of 1 - 10 digits.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowDefinitionsApi
     */
    public getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber(definitionId: string, versionNumber: string, options?: any) {
        return WorkflowDefinitionsApiFp(this.configuration).getV1WorkflowDefinitionsVersionsByDefinitionIdAndVersionNumber(definitionId, versionNumber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the model of the specified version of the specified workflow definition.   Roles permitted to execute this operation:  - Global roles:  WorkflowViewer, WorkflowAdmin, WorkflowDeveloper  - Scope: WORKFLOW_DEFINITION_GET_MODEL 
     * @summary Retrieve workflow definition model by ID and version number
     * @param {string} definitionId The workflow definition ID for which the model should be retrieved. The workflow definition ID is at most 64 characters long.
     * @param {string} versionNumber The version number for which the model should be retrieved. The version number consists of 1 - 10 digits.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowDefinitionsApi
     */
    public getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber(definitionId: string, versionNumber: string, options?: any) {
        return WorkflowDefinitionsApiFp(this.configuration).getV1WorkflowDefinitionsVersionsModelByDefinitionIdAndVersionNumber(definitionId, versionNumber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the default start context of the specified version of the specified workflow definition.  Roles permitted to execute this operation:  - Global roles:  WorkflowInitiator  - Scope: WORKFLOW_DEFINITION_GET_SAMPLE_CONTEXT 
     * @summary Retrieve sample start context of workflow definition by ID and version number
     * @param {string} definitionId The workflow definition ID for which the default start context should be retrieved. The workflow definition ID is at most 64 characters long.
     * @param {string} versionNumber The version number for which the default start context should be retrieved. The version number consists of 1 - 10 digits.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowDefinitionsApi
     */
    public getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber(definitionId: string, versionNumber: string, options?: any) {
        return WorkflowDefinitionsApiFp(this.configuration).getV1WorkflowDefinitionsVersionsSampleContextsDefaultStartContextByDefinitionIdAndVersionNumber(definitionId, versionNumber, options).then((request) => request(this.axios, this.basePath));
    }
}
